[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "altair>=5.5.0",
    "openai>=1.75.0",
    "pandas>=2.2.3",
    "streamlit>=1.44.1",
]
