[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "altair>=5.5.0",
    "anthropic>=0.49.0",
    "openai>=1.75.0",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
    "streamlit>=1.44.1",
]
